### ISSUE TITLE
Can't use createFile two times on the same workbook

### ISSUE THREAD

**Issue by ElodieC** [stephenliberty/excel-builder.js#12]
I can't call 2 times `ExcelBuilder.createFile()` on the same workbook object. There is no error but the Excel file is weird : the values are not in their right place the second time.
Here is an example code : 
```javascript
var workbook = ExcelBuilder.createWorkbook();
var worksheet = workbook.createWorksheet({name: 'worksheet 123'});
var data = [
  ['A1', '','A2'],
   ['B1', 'B2']
];
data.push([1,2,300]);
worksheet.setData(data);
workbook.addWorksheet(worksheet);
var blob = ExcelBuilder.createFile(workbook, {type:'blob'});
saveAs(blob, 'test.xlsx');
var blob2 = ExcelBuilder.createFile(workbook, {type:'blob'});
saveAs(blob2, 'test2.xlsx');
```
PS : I use the factory version

**Comment by stephenliberty** [comment]
For what it's worth (I realize this is several months late), the library was never built to keep state. Though it'd be more efficient to allow it to create workbook X and then workbook Y from the same code, it then starts to eat memory like mad.
