### ISSUE TITLE
How to access Excel submodules when using dist file?

### ISSUE THREAD

**Issue by viteksafronov** [stephenliberty/excel-builder.js#20]
There is an [example](http://excelbuilderjs.com/cookbook/tableSummaryRow.html) for tables which creates new Table() instance.
I use compiled dist file, and I get an error, Table is undefined.
How do I properly access submodules? Should I use the exposed ExcelBuilder variable or something else?

**Comment by stephenliberty** [comment]
Table isn't exposed in the current version. Working on a fix.
