### ISSUE TITLE
Insert empty value generating #ARG

### ISSUE THREAD

**Issue by Rzodkiewka** [stephenliberty/excel-builder.js#26]
Hello. 
Lately I have started using ExcelBuilder. Its awesome and thank you for that, it helped me a lot.
But I noticed some strange issue some time ago.

When I put empty value in the following way:
```javascript
someData.push('') //Lets say its a C4 cell (just random value)
```

then when I open created excel file, I can perform such a formula : =C4 + X5. And the result of this formula will be equal to 0.
But when I put empty values like this:
```javascript
someData.push({value: '', metadata{...}})
```
 and after trying to put the same formula from the previous "point" I am receiving such an error "#ARG"

I would like to put empty values with the help of the second command because I need to style those empty cells and then in the future use them again.

I would also like to know if there is any possiblity to put two styles in one metadata key. Like:
.. metadata: {style : [someStyle1.id, someStyle2.id]} (this solution is not working :))

Because right now I need to create new style for each different kind of looks. It will be nice to combine those styles like "style: [boldBorder.id backgroundRed.id] "etc.

**Comment by stephenliberty** [comment]
The multiple styles thing is probably a no-go right now. Excel's style stuff is complicated enough as it is.

Anyway, I think I know why that is happening.. but I don't have the bandwidth to fix the bug right now. Marking this as a bug to remind me next week.

**Comment by dbeulen** [comment]
Is there any progress on this issue? I need to format a cell, but is should remain empty. This because the text of the cell before it should come over the cell.

**Comment by stephenliberty** [comment]
I've poked at this a bit, but haven't been able to repro it. Possibly was fixed in a pull request that was brought in. If there's still an issue, please send me a link to the excel doc so I can deconstruct it.
