### ISSUE TITLE
How to make text wrap inside cells

### ISSUE THREAD

**Issue by nicolamontini** [stephenliberty/excel-builder.js#27]
I'd like to make text wrap inside cells, is there the possibility to do this? 
Thanks

**Comment by stephenliberty** [comment]
Yes. Just create a new format and in the format instructions set ```wrapText``` to ```true```.

**Comment by nicolamontini** [comment]
Thanks!

**Comment by tgourley** [comment]
For anyone who might want a little bit of code, it took me a while to realize this was an "alignment" option.  So to create a new format for wrapping the text in a cell do something like this...

//taken from the BasicReport.js demo
this.predefinedFormatters = {
     wrap: this.stylesheet.createFormat({
           alignment: { wrapText: true }
     })
};
