### ISSUE TITLE
Change border type 

### ISSUE THREAD

**Issue by nicolamontini** [stephenliberty/excel-builder.js#28]
I'd like to change the border of a cell and make a dashed border. Is it possible? I read in the cookbook that it's possible to change the color, but there are no hints about changing the border line style. Thanks

**Comment by stephenliberty** [comment]
You need to create a border formatter. So, using the stylesheet, run something like..

stylesheet.createBorderFormatter({
    top: {
        style: 'mediumDashed', //from http://www.schemacentral.com/sc/ooxml/t-ssml_ST_BorderStyle.html
        color: 'FF006666'
    }
});

Use that border formatter on any styles that need to be applied to cells. The borders are 'top', 'bottom', 'left', 'right', 'diagonal'.
