### ISSUE TITLE
Multiple styles in a cell

### ISSUE THREAD

**Issue by nicolamontini** [stephenliberty/excel-builder.js#31]
Let's assume I'm formatting the cell A1. I'd write:

{value: 'Artist', metadata: {style: formatterName.id}}

Is there the possibility to apply multiple styles (like I do when I apply multiple css classes to an html element) to the cell? Something similar to this:

{value: 'Artist', metadata: {style: [formatterName1.id, formatterName2.id]}}

This solution would save a lot of time and code to me. Thanks

**Comment by stephenliberty** [comment]
Unfortunately due to the complexity of how excel deals with styles, I'm not sure that's feasible right now. Put a bounty out on it and maybe someone will pick it up.
