### ISSUE TITLE
style problem on LibreOffice/OpenOffice

### ISSUE THREAD

**Issue by zerocl** [stephenliberty/excel-builder.js#34]
opening the generated file with OpenOffice/LibreOffice, none of the styles are applied (no borders, missing font and background colors, font names and sizes). However, the same file appears correctly, with all styles applied in MS Office.

**Comment by zerocl** [comment]
solved. sorry for messing up issues, i will make a pull request later on

**Comment by phihag** [comment]
Can you elaborate what you did do? I'm seeing the same problem.
