### ISSUE TITLE
Freeze row

### ISSUE THREAD

**Issue by ioankyp** [stephenliberty/excel-builder.js#40]
Hello,

Is there any way we can create a frozen row using the library?

**Comment by pulavska** [comment]
I'm also interested this functional. Is it possible to add method?

**Comment by stephenliberty** [comment]
This should exist in V1 (worksheet.freezePane(column, row, cell).

**Comment by bmanturner** [comment]
Looks like this has since been deprecated. What's the best way to go about this? A code example would be nice.

**Comment by stephenliberty** [comment]
Working on (slowly) moving documentation and rewriting examples to fit V2 format. Basically, the code you're looking for is..

`worksheet.sheetView.freezePane(column, row, cell)
`
This is short for..

```
var sheetView = new EB.SheetView()
sheetView.freezePane(column, row, cell)
var worksheet = new EB.Worksheet({
    sheetView: sheetView
});
```

The worksheet.freezePane is just a pass through to that method now - in the prior version the 'sheetView' didn't exist (or at least wasn't thought out).

**Comment by bmanturner** [comment]
If I just wanted to freeze the top row, what would I enter? Providing null for column and 1 for row does not work.
