### ISSUE TITLE
Downloading Problem with Chrome when Data size is huge

### ISSUE THREAD

**Issue by surajitdassoftwareag** [stephenliberty/excel-builder.js#42]
I have created ExcelBuilder file using JSON response. But unable to download it in the browser because its little big in size. So I tried to convert that download excelBuilder file object to BLOB object but download does not able to open the content (it gets encrypted). If i dont not use BLOB to convert the object then Chrome crushes it could not able to handle it. Please help me out.

**Comment by mohamedmohsin** [comment]
i also have same problem ,when data set size increases chrome browser crash

**Comment by stephenliberty** [comment]
How large of a data set are we talking? There are limits to this app. I think 30k rows with maybe 20 columns was the most that I ever put into a sheet.

**Comment by surajitdassoftwareag** [comment]
JSON response was for two sheets together. 
First sheet was size of : 24 columns x 200 rows (approx.)
Second sheet was size of : 18 columns x 100 rows (approx.)

Below this size of data, chrome was able to download.
As I am playing with huge data set more then 5000000, So now I have move to server side implementation.

**Comment by mohamedmohsin** [comment]
@stephenliberty  i have 25k rows and less than 20 column ,same problem persists

**Comment by stephenliberty** [comment]
@mohamedmohsin Sorry about the delay on getting back to you. I'm guessing you've moved on by now, but if the problem still persists please link back with a jsfiddle or something so I can take a look at the code you're running.

**Comment by mohamedmohsin** [comment]
@stephenliberty  i run your web worker example in your site  , for  both firefox and google chrome it generate am empty echo.php file
