### ISSUE TITLE
Hide Grid Lines

### ISSUE THREAD

**Issue by kfred** [stephenliberty/excel-builder.js#43]
Hi,

I would like to hide grid lines in my Excel file. According to the OOXML reference, there is an attribute called "showGridLines" which can be set to true or false (true by default).

How can I modify the excel-builder project to pass a true/false variable to showGridLines attribute when building the .xlsx fiile?:

http://www.datypic.com/sc/ooxml/a-showGridLines-1.html

Many thanks,
Kurt

**Comment by kfred** [comment]
Does anyone know how to hide grid lines? Since this omission is by far the greatest limitation of excel-builder, we should try to figure out how to add this.

**Comment by dbeulen** [comment]
A workaround in hiding the grid lines is setting all background to fill on a white color.

**Comment by stephenliberty** [comment]
Sheet view exposed in V2
