### ISSUE TITLE
add hyperlink to cell

### ISSUE THREAD

**Issue by peryamobee** [stephenliberty/excel-builder.js#44]
hello, 
there is any way to make text in cell as hyperlink ? 

I have a worksheet with column of links and I really want make the clickable. 
there is #8 with the same question but without clear solution 

Thanks

**Comment by menyalmog** [comment]
The following works:
```javascript
{ value: 'HYPERLINK("http://url.com","Link Text")', metadata: { type: 'formula' } }
```

**Comment by kfred** [comment]
@menyalmog do you know of a way to hide gridlines?

**Comment by stephenliberty** [comment]
Fixed in v2. Modeled off the weird spec from MS. Still need to document, but there is now a 'hyperlinks' array on a worksheet. Adding an object like the following will create a hyperlink on a cell, though the cell still needs content to be set separately.

`{
    location: 'http://www.google.com',
    ref: 'A2'
}`

**Comment by soullessknight** [comment]
@stephenliberty This library is awesome!  Just want to note on creating the hyperlink, I used "cell" instead of "ref".

`{ location: 'http://www.google.com', cell: 'A2' }`
