### ISSUE TITLE
Table and pictures together causes error

### ISSUE THREAD

**Issue by AdamPD** [stephenliberty/excel-builder.js#60]
If you try to add both a table and pictures/drawings to a worskheet, Excel 2013 will throw an error:

```Replaced Part: /xl/worksheets/sheet1.xml part with XML error.  Load error. Line 2, column 1254.```

It appears that the order of table and drawings is important and the way it currently works causes this.

https://gist.github.com/AdamPD/c2a20c4bd8a3c4d743e8 reproduces the issue.

**Comment by stephenliberty** [comment]
Fixed in V2
