### ISSUE TITLE
Exporting 2 worksheets one with tabular data and another one with base64 png image

### ISSUE THREAD

**Issue by chitraflorid** [stephenliberty/excel-builder.js#69]
Hi,

Anybody has tried exporting 2 worksheets, one with tabular data and another sheet with base64 image data???

Will it work?? 

Kindly let me know the possible implementation for this..

Thanks in advance.
Chitra

**Comment by chitraflorid** [comment]
I'm able to export 2 worksheets with tabular data and the image in each one of them. Hence, closing this issue

**Comment by stephenliberty** [comment]
Oh good, sorry - I'm working on the documentation but it's taking a lot longer than I was hoping.
