### ISSUE TITLE
Failed to execute 'createObjectURL' on 'URL'

### ISSUE THREAD

**Issue by camlizo** [stephenliberty/excel-builder.js#72]
Hi,

I try to create an xlsx file to export it thanks to FileSaver but I get the following error: 
```
Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided
```
My code is below:
```javascript
var workbook = ExcelBuilder.Builder.createWorkbook();
var worksheet = workbook.createWorksheet({ name: 'TestSheet' });
var stylesheet = workbook.getStyleSheet();
…
var blob = ExcelBuilder.Builder.createFile(workbook, {type: "blob"});
saveAs(blob, "sample.xlsx");
```

Whereas inside a block like this :
```javascript
ExcelBuilder.Builder.createFile(workbook, {type: "blob"}).then(function(data){
saveAs(data, "sample.xlsx");
})
```

the 'data' is correct but nothing is happening. 

Any idea how to solve this problem ?

Thanks

**Comment by stephenliberty** [comment]
So, the second way is the right way, but I'm not sure why that isn't working for you. I'll try and investigate this evening while writing more documentation.

**Comment by camlizo** [comment]
I finally found the solution:
```javascript
ExcelBuilder.Builder.createFile(workbook, {type: "blob"}).then(function(data){
	return saveAs(data, "sample.xlsx");
})
```
But I really don’t know why the first solution doesn't work anymore like in these two examples: #4 and #12 
Thanks Stephen

**Comment by stephenliberty** [comment]
The API changed a bit, hence why the old solutions aren't working anymore. I think that was really only one of two breaking changes between v1 and v2 - the other being that the library is no longer setup to use requirejs.
